FROM node:18-alpine AS build

WORKDIR /app

COPY package.json pnpm-lock.yaml* ./

RUN pnpm install --frozen-lockfile

COPY . .
RUN pnpm run build

FROM node:18-alpine

WORKDIR /app

COPY package.json pnpm-lock.yaml* ./
RUN pnpm install --frozen-lockfile --production

COPY --from=build /app/dist ./dist

EXPOSE 3002

CMD ["node", "dist/index.js"]
    